export {default as Header} from './Header'
export {default as Hero } from './Hero'
export {default as BackgroundCircles} from './BackgroundCircles'
export {default as About} from './About'
export {default as Projects} from './Projects'